repos:
- hooks:
  - id: check-ast
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: ^.github/
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.39.1
- hooks:
  - id: black
    exclude: ^.github/
  repo: https://github.com/psf/black
  rev: 22.12.0
