name: whatday-dev
channels:
  - conda-forge
dependencies:
  - python==3.11.0
  - pip==22.3.1
  - mypy==0.991
  - pylint==2.15.10
  - black==22.12.0
  - pre-commit==2.21.0
  - commitizen==2.28.1
  - pip:
      - pymarkdownlnt==0.9.8
