name: "Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittest:
    name: "Python unittest on ${{ matrix.platform }}"
    strategy:
      matrix:
        platform:
          - ubuntu-22.04
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{hashFiles('environment-dev.yml') }}
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment-dev.yml
          channel-priority: strict
          activate-environment: whatday-dev
      - run: conda info
      - run: python3 -m unittest discover test
